server {
    listen 80;

    # Interceptar erros vindos do proxy
    proxy_intercept_errors on;

    # O que for para a API, mandamos para o container do Node.
    location /api/ {
        proxy_pass http://backend:3333/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # O que for o site (React)
    location / {
        proxy_pass http://frontend:5173/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        # Se o Vite der erro de conexão (502, 503 ou 504), 
        # o Nginx vai procurar a página definida abaixo
        error_page 502 503 504 = /manutencao.html;
    }

    location = /manutencao.html {
        root /usr/share/nginx/html;
        internal;
    }
}